### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by fdn** [psayre23/WebSQL#1]
What is this code licensed under?

**Comment by psayre23** [comment]
It isn't under any license. It is free code you found on the web. Do you have a need to have this licensed under something specific?

**Comment by fdn** [comment]
If you could license under MIT or Apache that would be great.

Guerric

**Comment by psayre23** [comment]
Can you describe your need? Before I attach a license to my code I'd like
to know what for. I'm not against it, I just want it thought through.

**Comment by fdn** [comment]
Sure. The project I'm working on will only allow me to use licensed code. Since I'ld like to use your library, I'ld like you to throw a license on it. If you'ld rather not, I understand. But at the same time not having a license might be limiting other people from using your library as well.

**Comment by psayre23** [comment]
MIT it is. I think that fits well with the reason I put the code up on
GitHub. I'll mark it in the repo today and close the ticket once it's done.
Thank you for reaching out on this.
